export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE'
export const INICIO_SESION_EXITOSO = 'INICIO_SESION_EXITOSO'
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR'

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'

export const CERRAR_SESION = 'CERRAR_SESION'