export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'

export const INICIO_SESION_EXITOSO = 'INICIO_SESION_EXITOSO'
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR'

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'
export const CERRAR_SESION = 'CERRAR_SESION'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE'

export const CARGANDO = 'CARGANDO'
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO'
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR'


export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO'
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR'

export const LIMPIAR_STATE = 'LIMPIAR_STATE'

export const CAMBIO_CANTIDAD_DESCARGAS = 'CAMBIO_CANTIDAD_DESCARGAS'
export const CAMBIO_CLAVE = 'CAMBIO_CLAVE'

export const CLAVE_VERIFICADA_EXITO = 'CLAVE_VERIFICADA_EXITO'
export const CLAVE_VERIFICADA_ERROR = 'CLAVE_VERIFICADA_ERROR'